sudo: required

services:
  - docker

before_install:
  - docker version
  - sudo apt-get -y install python-pip
  - sudo pip install docker==2.7.0 docker-squash
  - docker build -t nanobox/pulse .

script: sudo test/run_all.sh

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/pulse .
  - docker-squash -t ${NAMESPACE}/pulse:squashed -f nanobox/runit --tmp-dir /var/tmp/squasher ${NAMESPACE}/pulse
  - docker tag ${NAMESPACE}/pulse:squashed ${NAMESPACE}/pulse:beta;
  - docker push ${REMOTE}${NAMESPACE}/pulse:beta;
  - if [ "$BRANCH" == "master" ]; then
    docker tag ${NAMESPACE}/pulse:squashed ${NAMESPACE}/pulse;
    docker push ${REMOTE}${NAMESPACE}/pulse;
    else
    docker tag ${NAMESPACE}/pulse:squashed ${NAMESPACE}/pulse:${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/pulse:${BRANCH//\//_};
    fi
